services:
  clipbin:
    container_name: clipbin
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        environment: development
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
